checksumBehavior: update

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"

changesetBaseRefs:
  - main
  - origin/main
  - upstream/main

yarnPath: .yarn/releases/yarn-2.2.2.cjs
